sudo: false

language: "python"

branches:
  only:
    - master

matrix:
  include:
    - python: "pypy"
    - python: "2.7"

install:
  - |
    if [ "${TRAVIS_PYTHON}" == "pypy" ]; then
      git clone --depth 1 https://github.com/yyuu/pyenv.git ~/.pyenv
      PYENV_ROOT="$HOME/.pyenv"
      PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      pyenv install pypy-5.4
      pyenv global pypy-5.4
    fi
  - pip install -U pip setuptools wheel
  - pip install coveralls coverage
  - pip install .

script:
  - coverage run --branch --source=epsilon $(type -p trial) epsilon
  - coverage report -m

after_success:
  - coveralls

notifications:
  email: false
  irc:
     channels: "chat.freenode.net#divmod"
     template:
       - "%{repository}@%{branch} - %{author}: %{message} (%{build_url})"
     use_notice: true
