sudo: false

language: "python"

branches:
  only:
    - master

python:
  - 2.7

env:
  - TOXENV=py27
  - TOXENV=pypy

install:
  - pip install -U pip setuptools wheel
  - pip install coveralls coverage
  - |
    if [ "${TOXENV::4}" == "pypy" ]; then
      git clone --depth 1 https://github.com/yyuu/pyenv.git ~/.pyenv
      PYENV_ROOT="$HOME/.pyenv"
      PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      pyenv install pypy-5.4
      pyenv global pypy-5.4
    fi

script:
  - tox

after_success:
  - codecov

notifications:
  email: false
  irc:
     channels: "chat.freenode.net#divmod"
     template:
       - "%{repository}@%{branch} - %{author}: %{message} (%{build_url})"
     use_notice: true
