sudo: false

language: "python"

branches:
  only:
    - master

matrix:
  include:
    - python: "pypy"
    - python: "2.7"

install:
  # Upgrade packaging tools first
  - pip install -U pip setuptools wheel
  # Tools for checking coverage and uploading to coveralls
  - pip install coveralls coverage
  - pip install "cryptography<1.0.0" .

script:
  - coverage run --branch --source=epsilon $(type -p trial) epsilon
  - coverage report -m

after_success:
  - coveralls

notifications:
  email: false
  irc:
     channels: "chat.freenode.net#divmod"
     template:
       - "%{repository}@%{branch} - %{author}: %{message} (%{build_url})"
     use_notice: true
